Repository OCA/connector, pull requests merged in 2020-05, with the labels that each got.

#368 [13.0] Update pre-commit config [needs fixing]
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#371 Recover the v13 new feature of create method with a list of vals on Base
  component_event/models/base.py
Labels: approved, bot is merging ⏳

#343 [ADD] configurable scheme, host and http auth
  connector/jobrunner/__init__.py
  connector/jobrunner/runner.py
Labels: approved
