Repository OCA/connector, pull requests merged in 2021-06, with the labels that each got.

#401 14.0 component: improve README
  component/readme/USAGE.rst
Labels: approved, bot is merging ⏳, ready to merge

#396 [10.0][ADD] connector new icon
  connector/connector_menu.xml
  connector/static/description/icon.png
Labels: approved, bot is merging ⏳, ready to merge

#400 13.0 component: improve README
  component/readme/USAGE.rst
Labels: approved, bot is merging ⏳

#383 [FIX][10.0] When searching for bindings, also find inactive ones
  connector/components/synchronizer.py
Labels: bot is merging ⏳

#405 [14.0][MIG] connector_base_product
  connector_base_product/README.rst
  connector_base_product/__init__.py
  connector_base_product/__manifest__.py
  connector_base_product/i18n/ca.po
  connector_base_product/i18n/connector_base_product.pot
  connector_base_product/i18n/de.po
  connector_base_product/i18n/es.po
  connector_base_product/i18n/fr.po
  connector_base_product/i18n/hu.po
  connector_base_product/i18n/it.po
  connector_base_product/i18n/nl.po
  connector_base_product/i18n/pt_BR.po
  connector_base_product/i18n/sl.po
  connector_base_product/i18n/zh_CN.po
  connector_base_product/readme/CONTRIBUTORS.rst
  connector_base_product/readme/DESCRIPTION.rst
  connector_base_product/static/description/icon.png
  connector_base_product/static/description/index.html
  connector_base_product/views/product_view.xml
  setup/connector_base_product/odoo/addons/connector_base_product
  setup/connector_base_product/setup.py
Labels: bot is merging ⏳

#386 [13.0][MIG] connector_base_product
  connector_base_product/__manifest__.py
Labels: approved, bot is merging ⏳

#408 component_event: fix unit test w/ odoo test suite
  component_event/tests/test_event.py
  connector/tests/test_mapper.py
Labels: approved, bot is merging ⏳
